<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
  margin-top: 30px;
}

td,
th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.andrew-test {
  color: #04a57a;
}
</style>

<table>
  <tr>
    <th>Fedex ID</th>
    <th>Tracking</th>
    <th>Created</th>
  </tr>
  <?php
        foreach ($block->getFedexCollection() as $key=>$fedex){
          echo '<tr>
            <td>'.$fedex->getFedexId().'</td>
            <td>'.$fedex->getQuestion().'</td>
            <td>'.$fedex->getCreatedAt().'</td>
            </tr>';
        }
    ?>
</table>

<div>
  <?php foreach ($block->getFedexCollection() as $key=>$fedex){ ?>
  <div class="andrew-test">
    <?php echo $fedex->getQuestion() ?>
  </div>
  <?php } ?>
</div>

</body>

</html>